### ISSUE TITLE
compiler.parser is deprecated, and compiler.parser.evaluate is not a function. 

### ISSUE THREAD

**Issue by xinghengwang** [nwinch/webpack-dotenv-plugin#17]
webpack: Using compiler.parser is deprecated.
Use compiler.plugin("compilation", function(compilation, data) {
  data.normalModuleFactory.plugin("parser", function(parser, options) { parser.plugin(/* ... */); });
}); instead. It was called at /****/node_modules/webpack-dotenv-plugin/node_modules/webpack/lib/DefinePlugin.js:52:20.
TypeError: compiler.parser.evaluate is not a function

**Comment by nwinch** [comment]
Thanks @xinghengwang. What version of webpack did this issue occur with?

**Comment by xinghengwang** [comment]
you are right, I used a wrong version. updated and fixed the issue.
