### ISSUE TITLE
Variables defined optionally in env file are not passed

### ISSUE THREAD

**Issue by Stene3** [nwinch/webpack-dotenv-plugin#6]
Hi,
I'm not sure, if I understand the concept of this plugin well, but when I tried to define my scenario, it does not work. I will try to describe my expectations:

1) I have env file with 2 variables:

```
RAVEN_DSN=https://log.xyz.cz...
DEBUG=1
```

2) I have an example file with 1 variable:

```
RAVEN_DSN=https://log.xyz.cz...
```

> There's just 1 variable. There's no need to mention `DEBUG` variable since it's optional.

I would expect, that both `RAVEN_DSN` and `DEBUG` variables will be passed to the `process.env`, but there's only `RAVEN_DSN` presented, because the list of variables is loaded from **example** file. How one could handle the optional variables? Is that possible?

What about to load all variables from the `.env` file, then iterate over all variables from the example and check whether all variables from the example were set or not?

**Comment by nwinch** [comment]
Thanks @Stene3.  We could use `.env` as the blueprint, but then would lose the error checking that `dotenv-safe` provides by using `example` as the master list.  An easy solution might be just to add `DEBUG=0` to `example.env` and simply set it to `1` when needed, as you've done in your above example.  Would that suffice for your needs?

I think it's more manageable to ensure both example and env list the same variables to ensure consistency, so am hesitant to introduce functionality for optional env vars if not absolutely necessary.

**Comment by Stene3** [comment]
Hi @nwinch. Thanks! It sounds reasonable to me.
